apiVersion: v1
kind: Service
metadata:
  name: turboserve-engine
  labels:
    app.kubernetes.io/component: engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: engine
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
